### ISSUE TITLE
How to build in Mac OS Catalina?

### ISSUE THREAD

**Issue by planktonwhc** [NyanSatan/checkm8_bootkit#1]
i tryng to make file using catalina, and show eror llvm bin notfound

**Comment by NyanSatan** [comment]
You gotta have an ARM compiler toolchain in order to build the payload. I usually use LLVM built from source, but you can find prebuilt GCC one online. Example for building with another toolchain is in README

**Comment by planktonwhc** [comment]
plankton@MBP-PLANKTON checkm8_bootkit % TOOLCHAIN=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin ARM_CC=cc ARM_OBJCOPY=arm-none-eabi-objcopy make       
clang: warning: argument unused during compilation: '-mthumb' [-Wunused-command-line-argument]
error: unknown target CPU 'armv7-a'
note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, rocketlake, icelake-server, tigerlake, sapphirerapids, alderlake, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, znver3, x86-64, x86-64-v2, x86-64-v3, x86-64-v4
make: *** [build/src/libbootkit/payload/payload.o] Error 1


still cant build, how to fix ??

**Comment by NyanSatan** [comment]
You need a toolchain capable of building ARM binaries in ELF format, not the x86 one bundled with Xcode

**Comment by NyanSatan** [comment]
Latest update doesn't require GCC toolchain, but Xcode+vmacho instead. Also it includes already compiled payloads

**Comment by gokl1999** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
