### ISSUE TITLE
Error building on catalina

### ISSUE THREAD

**Issue by amats211** [NyanSatan/checkm8_bootkit#2]
Hi sir,

Trying to build it on catalina but having error..

Here is logs:

Macs-MacBook-Pro:watch mac$ cd checkm8_bootkit/
Macs-MacBook-Pro:checkm8_bootkit mac$ TOOLCHAIN=/opt/gcc-arm-none-eabi-7-2018-q2-update/bin ARM_CC=arm-none-eabi-gcc ARM_OBJCOPY=arm-none-eabi-objcopy make
make: bin2c: No such file or directory
make: *** [src/libbootkit/payload.h] Error 1

**Comment by NyanSatan** [comment]
Yea, build system for this one is really bad

There’s bin2c source code in `tools/`

Build it and install to PATH

**Comment by amats211** [comment]
Thank you very much, build done..

Macs-MacBook-Pro:checkm8_bootkit mac$ TOOLCHAIN=/opt/gcc-arm-none-eabi-7-2018-q2-update/bin ARM_CC=arm-none-eabi-gcc ARM_OBJCOPY=arm-none-eabi-objcopy make
	building C: src/main.c
	building C: src/libbootkit/libbootkit.c
	linking
%%%%% done building
